-- Trial migration for draw history storage.
-- This keeps Firebase Auth as-is and moves draw_entries into Supabase first.
-- If you later migrate auth as well, tighten the RLS policies below.

create table if not exists public.draw_entries (
    id bigint generated by default as identity primary key,
    round integer not null check (round > 0),
    numbers integer[] not null,
    numbers_key text not null check (char_length(numbers_key) between 11 and 20),
    set_no integer not null check (set_no between 1 and 20),
    source_mode text not null check (source_mode in ('self', 'premium')),
    strategy text,
    user_type text not null check (user_type in ('guest', 'member')),
    membership_tier text not null check (char_length(membership_tier) between 1 and 40),
    uid text,
    guest_tracking_id text,
    generation_id text not null check (char_length(generation_id) between 10 and 64),
    rule_ids text[] not null default '{}',
    rule_count integer not null default 0 check (rule_count between 0 and 80),
    created_at timestamptz not null default timezone('utc', now()),
    constraint draw_entries_numbers_length check (array_length(numbers, 1) = 6),
    constraint draw_entries_numbers_range check (
        numbers[1] between 1 and 45
        and numbers[2] between 1 and 45
        and numbers[3] between 1 and 45
        and numbers[4] between 1 and 45
        and numbers[5] between 1 and 45
        and numbers[6] between 1 and 45
    ),
    constraint draw_entries_numbers_sorted check (
        numbers[1] < numbers[2]
        and numbers[2] < numbers[3]
        and numbers[3] < numbers[4]
        and numbers[4] < numbers[5]
        and numbers[5] < numbers[6]
    ),
    constraint draw_entries_guest_member_shape check (
        (user_type = 'guest' and uid is null)
        or (user_type = 'member' and uid is not null)
    )
);

create index if not exists draw_entries_created_at_idx on public.draw_entries (created_at desc);
create index if not exists draw_entries_round_idx on public.draw_entries (round);
create index if not exists draw_entries_uid_idx on public.draw_entries (uid);
create index if not exists draw_entries_guest_tracking_id_idx on public.draw_entries (guest_tracking_id);
create index if not exists draw_entries_generation_id_idx on public.draw_entries (generation_id);

alter table public.draw_entries enable row level security;

drop policy if exists "draw_entries_public_read" on public.draw_entries;
create policy "draw_entries_public_read"
on public.draw_entries
for select
to anon, authenticated
using (true);

drop policy if exists "draw_entries_public_insert" on public.draw_entries;
create policy "draw_entries_public_insert"
on public.draw_entries
for insert
to anon, authenticated
with check (true);
